### ISSUE TITLE
What does the big warning really mean?

### ISSUE THREAD

**Issue by danielbprice** [t-yuki/gocover-cobertura#6]
"**NOW WORKING BUT NOT ACCURATE**" at the top of the page for this project.

I can't interpret this.  I see that this project is active-- which is great!-- but I don't know whether you think it is working properly.  Can you clarify?

**Comment by t-yuki** [comment]
At the time I created this command several years ago, it produces different output compared to gocov  toolchain (https://github.com/axw/gocov and https://github.com/AlekSi/gocov-xml).
Sorry, I can't remember more details...
I removed the notice since that is confusing.

**Comment by danielbprice** [comment]
Thanks!
